import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../../services/supabase'
import '../../styles/layout/sidebarGlobal.css'

const gruposBase=[
  {titulo:'Principal',itens:[{id:'inicio',icone:'🏠',rotulo:'Início'},{id:'guia',icone:'🧭',rotulo:'Como Jogar',href:'/guia'},{id:'perfil',icone:'👤',rotulo:'Meu Perfil'},{id:'perfil-publico',icone:'🌐',rotulo:'Perfil Público',href:'/?pagina=perfil-publico'},{id:'comunidade-social',icone:'🤝',rotulo:'Comunidade',href:'/comunidade'},{id:'mural-comunidade',icone:'📌',rotulo:'Mural Social',href:'/mural'},{id:'chat-privado',icone:'💬',rotulo:'Chat Privado',href:'/chat'},{id:'servidores',icone:'🏰',rotulo:'Servidores',href:'/servidores'},{id:'notificacoes',icone:'🔔',rotulo:'Notificações',href:'/notificacoes'},{id:'diario-personagem',icone:'📖',rotulo:'Diário'},{id:'pets',icone:'🐾',rotulo:'Companheiros'}]},
  {titulo:'Escola',itens:[{id:'tribos-completas',icone:'🛡️',rotulo:'Tribos',href:'/tribos'},{id:'rotina-escolar',icone:'🗓️',rotulo:'Rotina Escolar',href:'/rotina'},{id:'aulas',icone:'🎓',rotulo:'Sistema Acadêmico'},{id:'biblioteca',icone:'📚',rotulo:'Biblioteca'},{id:'profissoes',icone:'🧰',rotulo:'Profissões',href:'/profissoes'},{id:'jornal',icone:'📰',rotulo:'Jornal',href:'/jornal'},{id:'temporadas',icone:'🍃',rotulo:'Temporadas',href:'/temporadas'},{id:'quadro-avisos',icone:'📜',rotulo:'Quadro de Avisos'}]},
  {titulo:'Interpretação',itens:[{id:'rpg-textual',icone:'🪶',rotulo:'RPG Textual',href:'/rpg'}]},
  {titulo:'Exploração',itens:[{id:'exploracao',icone:'🗺️',rotulo:'Explorar Castelobruxo',href:'/exploracao'},{id:'colecoes',icone:'🗝️',rotulo:'Coleções e Códice',href:'/colecoes'},{id:'missoes',icone:'🧭',rotulo:'Missões'},{id:'eventos',icone:'📅',rotulo:'Eventos'}]},
  {titulo:'Economia',itens:[{id:'banco',icone:'🏦',rotulo:'Banco'},{id:'mercado',icone:'🛒',rotulo:'Mercado'},{id:'inventario',icone:'🎒',rotulo:'Inventário'}]},
  {titulo:'Registros',itens:[{id:'correio-magico',icone:'✉️',rotulo:'Correio Mágico'},{id:'conquistas',icone:'🏆',rotulo:'Conquistas'},{id:'certificados',icone:'📜',rotulo:'Certificados'}]}
]
function navegar(item){if(item.href){window.location.assign(item.href);return}window.dispatchEvent(new CustomEvent('castelobruxo:navegar',{detail:{pagina:item.id}}))}
export default function SidebarGlobal(){
  const [sessao,setSessao]=useState(null),[perfil,setPerfil]=useState(null),[aberta,setAberta]=useState(false)
  const [paginaAtual,setPaginaAtual]=useState(()=>{const p=location.pathname;if(p.startsWith('/guia'))return'guia';if(p.startsWith('/admin-profissoes'))return'admin-profissoes';if(p.startsWith('/temporadas'))return'temporadas';if(p.startsWith('/jornal'))return'jornal';if(p.startsWith('/rpg'))return'rpg-textual';if(p.startsWith('/rotina'))return'rotina-escolar';if(p.startsWith('/tribos'))return'tribos-completas';if(p.startsWith('/comunidade'))return'comunidade-social';if(p.startsWith('/mural'))return'mural-comunidade';if(p.startsWith('/chat'))return'chat-privado';if(p.startsWith('/servidores'))return'servidores';if(p.startsWith('/notificacoes'))return'notificacoes';if(p.startsWith('/moderacao-social'))return'moderacao-social';if(p.startsWith('/colecoes'))return'colecoes';if(p.startsWith('/exploracao'))return'exploracao';if(p.startsWith('/profissoes'))return'profissoes';return new URLSearchParams(location.search).get('pagina')||'inicio'})
  useEffect(()=>{let ativo=true;async function carregar(s){if(!s?.user){setPerfil(null);return}const{data,error}=await supabase.from('perfis').select('id,usuario,nome_personagem,avatar_url,cargo,tribo,nivel').eq('id',s.user.id).maybeSingle();if(!error&&ativo)setPerfil(data??null)}async function iniciar(){const{data}=await supabase.auth.getSession();if(!ativo)return;setSessao(data.session);await carregar(data.session)}iniciar();const{data}=supabase.auth.onAuthStateChange(async(_,s)=>{setSessao(s);await carregar(s)});const ouvir=e=>{if(e.detail?.pagina){setPaginaAtual(e.detail.pagina);setAberta(false)}};window.addEventListener('castelobruxo:pagina-alterada',ouvir);return()=>{ativo=false;data.subscription.unsubscribe();window.removeEventListener('castelobruxo:pagina-alterada',ouvir)}},[])
  useEffect(()=>{const exibir=Boolean(sessao&&perfil);document.body.classList.toggle('cb-com-sidebar',exibir);return()=>document.body.classList.remove('cb-com-sidebar')},[sessao,perfil])
  useEffect(()=>{document.body.classList.toggle('cb-sidebar-mobile-aberta',aberta);return()=>document.body.classList.remove('cb-sidebar-mobile-aberta')},[aberta])
  const grupos=useMemo(()=>{if(!perfil||!['professor','administrador'].includes(perfil.cargo))return gruposBase;const itens=[{id:'painel-professor',icone:'👨‍🏫',rotulo:'Painel do Professor'},{id:'painel-administrativo',icone:'🛡️',rotulo:'Painel Administrativo'},{id:'cms-conteudo',icone:'🧰',rotulo:'CMS de Conteúdo'},{id:'moderacao-social',icone:'⚖️',rotulo:'Moderação Social',href:'/moderacao-social'},{id:'jornal-editorial',icone:'🗞️',rotulo:'Redação do Jornal',href:'/jornal'}];if(perfil.cargo==='administrador'){itens.push({id:'admin-profissoes',icone:'💼',rotulo:'Gestão de Profissões',href:'/admin-profissoes'});itens.push({id:'admin-temporadas',icone:'🍂',rotulo:'Gestão de Temporadas',href:'/temporadas'})}return[...gruposBase,{titulo:'Gestão',itens}]},[perfil])
  function abrirItem(item){setAberta(false);window.setTimeout(()=>navegar(item),50)}
  if(!sessao||!perfil)return null;const nome=perfil.nome_personagem||perfil.usuario
  return <><button type="button" className="cb-sidebar-toggle" onClick={()=>setAberta(v=>!v)} aria-label={aberta?'Fechar menu':'Abrir menu'} aria-expanded={aberta}>{aberta?'✕':'☰'}</button>{aberta&&<div className="cb-sidebar-overlay" onClick={()=>setAberta(false)} role="presentation"/>}<aside className={`cb-sidebar-global ${aberta?'cb-sidebar-aberta':''}`} aria-hidden={!aberta&&window.innerWidth<=900}><header className="cb-sidebar-perfil"><div className="cb-sidebar-avatar">{perfil.avatar_url?<img src={perfil.avatar_url} alt={nome}/>:<span>👤</span>}</div><div><small>Estudante</small><strong>{nome}</strong><span>{perfil.tribo||'Sem tribo'} · Nível {perfil.nivel||1}</span></div></header><nav className="cb-sidebar-nav">{grupos.map(g=><section key={g.titulo}><h3>{g.titulo}</h3>{g.itens.map(i=><button key={i.id} type="button" className={paginaAtual===i.id?'cb-sidebar-item cb-sidebar-item-ativo':'cb-sidebar-item'} onClick={()=>abrirItem(i)}><span>{i.icone}</span><strong>{i.rotulo}</strong></button>)}</section>)}</nav><footer className="cb-sidebar-footer"><span>Castelobruxo</span><small>Conhecer · Respeitar · Proteger</small></footer></aside></>
}