import { useMemo, useState } from 'react'
import { supabase } from '../services/supabase'
import Notificacao from '../components/Notificacao'
import '../styles/inventario.css'

function normalizarCategoria(valor=''){return String(valor||'Outros').trim()}
const PASTAS_ITENS={ART:'ART',CRI:'CRIS',LIV:'LIV',PLA:'PLA',POT:'POT',UTE:'UTE',VES:'VEST'}
function imagemDoItem(item){if(!item)return'';if(item.imagem_url||item.image_url||item.url_imagem)return item.imagem_url||item.image_url||item.url_imagem;if(!item.imagem||!item.id||item.imagem==='placeholder.webp')return'';const prefixo=String(item.id).slice(0,3);if(['UNI','MAT','COM','ESC','BRO'].includes(prefixo))return`/assets/market/${item.imagem}`;const pasta=PASTAS_ITENS[prefixo];return pasta?`/assets/${pasta}/${item.imagem}`:''}
function slotDoItem(item={}){const codigo=String(item.id||item.codigo||'').toUpperCase();const cat=normalizarCategoria(item.categoria||item.tipo).toLowerCase();if(codigo.startsWith('VES')||['vestimentas','vestimenta','roupas','roupa'].includes(cat))return'traje';if(codigo.startsWith('ART')||['artefatos','artefato'].includes(cat))return'artefato';if(codigo.startsWith('UTE')||['utensílios','utensilios','utensílio','utensilio'].includes(cat))return'utensilio';if(codigo.startsWith('CRI')||['cristais','cristal','acessórios','acessorios','acessório','acessorio'].includes(cat))return'acessorio';return null}
const nomesSlots={traje:'Traje',acessorio:'Acessório',artefato:'Artefato',utensilio:'Utensílio'}

export default function Inventario({perfil,registros=[],mensagem,onAbrirMercado,onVoltar}){
 const [busca,setBusca]=useState(''),[categoria,setCategoria]=useState('Todos'),[aviso,setAviso]=useState(''),[acao,setAcao]=useState(false)
 const [equipados,setEquipados]=useState({traje:perfil?.traje_equipado||null,acessorio:perfil?.acessorio_equipado||null,artefato:perfil?.artefato_equipado||null,utensilio:perfil?.utensilio_equipado||null})
 const categorias=useMemo(()=>['Todos',...new Set(registros.map(r=>normalizarCategoria(r.item?.categoria||r.item?.tipo)).filter(Boolean))],[registros])
 const registrosFiltrados=useMemo(()=>{const termo=busca.trim().toLowerCase();return registros.filter(r=>{const i=r.item||{},cat=normalizarCategoria(i.categoria||i.tipo);return(categoria==='Todos'||cat===categoria)&&(!termo||String(i.nome||'').toLowerCase().includes(termo)||String(i.descricao||'').toLowerCase().includes(termo))})},[registros,busca,categoria])
 const totalUnidades=useMemo(()=>registros.reduce((t,r)=>t+Number(r.quantidade||0),0),[registros])
 async function equipar(registro){setAcao(true);setAviso('');const{data,error}=await supabase.rpc('equipar_item_personagem',{p_inventario_id:registro.id});if(error)setAviso(error.message||'Não foi possível equipar.');else{setEquipados(v=>({...v,[data.slot]:data.codigo}));setAviso(`${data.nome} equipado em ${nomesSlots[data.slot]}.`)}setAcao(false)}
 async function desequipar(slot){setAcao(true);setAviso('');const{error}=await supabase.rpc('desequipar_item_personagem',{p_slot:slot});if(error)setAviso(error.message||'Não foi possível desequipar.');else{setEquipados(v=>({...v,[slot]:null}));setAviso(`${nomesSlots[slot]} removido.`)}setAcao(false)}
 return <main className="inventario-pagina"><div className="inventario-topo-acoes"><button type="button" onClick={onVoltar}>← Voltar</button><button type="button" onClick={onAbrirMercado}>🛒 Ir ao mercado</button></div><header className="inventario-hero"><p>Bolsa pessoal</p><h1>Inventário</h1><span>Itens de <strong>{perfil?.nome_personagem||perfil?.usuario}</strong></span><div className="inventario-resumo"><article><small>Tipos de item</small><strong>{registros.length}</strong></article><article><small>Total de unidades</small><strong>{totalUnidades}</strong></article></div></header>
 <section className="inventario-equipamentos"><h2>Equipamentos ativos</h2><div>{Object.entries(nomesSlots).map(([slot,nome])=><article key={slot}><small>{nome}</small><strong>{equipados[slot]||'Nenhum'}</strong>{equipados[slot]&&<button disabled={acao} onClick={()=>desequipar(slot)}>Desequipar</button>}</article>)}</div></section>
 <section className="inventario-filtros"><label><span>Pesquisar</span><input type="search" placeholder="Pesquisar item" value={busca} onChange={e=>setBusca(e.target.value)}/></label><label><span>Categoria</span><select value={categoria} onChange={e=>setCategoria(e.target.value)}>{categorias.map(o=><option key={o}>{o}</option>)}</select></label></section><Notificacao mensagem={aviso||mensagem}/>
 {registros.length===0?<section className="inventario-vazio"><span>🎒</span><h2>Seu inventário está vazio</h2><p>Visite o Mercado das Cinco Trilhas para adquirir seus primeiros itens.</p><button type="button" onClick={onAbrirMercado}>Abrir mercado</button></section>:registrosFiltrados.length===0?<section className="inventario-vazio"><h2>Nenhum item encontrado</h2><p>Tente alterar a pesquisa ou categoria.</p></section>:<section className="inventario-grade">{registrosFiltrados.map(registro=>{const item=registro.item||{},imagem=imagemDoItem(item),slot=slotDoItem(item),codigo=String(item.id||item.codigo||'');const ativo=slot&&equipados[slot]===codigo;return <article className="inventario-item" key={registro.id}><div className="inventario-item-imagem">{imagem?<img src={imagem} alt={item.nome}/>:<span>✦</span>}<strong>×{Number(registro.quantidade||0)}</strong></div><div className="inventario-item-conteudo"><small>{normalizarCategoria(item.categoria||item.tipo)}</small><h2>{item.nome}</h2><p>{item.descricao||'Item mágico guardado no inventário.'}</p>{slot&&<button disabled={acao||ativo} onClick={()=>equipar(registro)}>{ativo?'Equipado':`Equipar como ${nomesSlots[slot]}`}</button>}{registro.adquirido_em&&<time>Adquirido em {new Date(registro.adquirido_em).toLocaleDateString('pt-BR')}</time>}</div></article>})}</section>}</main>
}
