import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../services/supabase'
import '../styles/social-final.css'

export default function ModeracaoSocialStandalone(){
  const [perfil,setPerfil]=useState(null),[denuncias,setDenuncias]=useState([]),[filtro,setFiltro]=useState('aberta'),[aviso,setAviso]=useState('')
  useEffect(()=>{iniciar()},[])
  async function iniciar(){const {data:{session}}=await supabase.auth.getSession(); if(!session)return; const {data:p}=await supabase.from('perfis').select('id,usuario,nome_personagem,cargo').eq('id',session.user.id).single(); setPerfil(p); if(['professor','administrador'].includes(p?.cargo))carregar()}
  async function carregar(){const {data,error}=await supabase.from('social_denuncias').select('*,denunciante:perfis!social_denuncias_denunciante_id_fkey(usuario,nome_personagem),moderador:perfis!social_denuncias_moderador_id_fkey(usuario,nome_personagem)').order('criado_em',{ascending:false}); if(error)return setAviso('Não foi possível carregar as denúncias.'); setDenuncias(data||[])}
  async function resolver(d,status){const decisao=prompt('Registre a decisão de moderação:'); if(!decisao)return; const {error}=await supabase.rpc('social_moderar_denuncia',{p_denuncia:d.id,p_status:status,p_decisao:decisao}); if(error)return setAviso(error.message); setAviso('Denúncia atualizada.'); carregar()}
  const lista=useMemo(()=>denuncias.filter(d=>filtro==='todas'||d.status===filtro),[denuncias,filtro])
  if(!perfil)return <main className="sf-shell"><p>Carregando moderação...</p></main>
  if(!['professor','administrador'].includes(perfil.cargo))return <main className="sf-shell sf-center"><h1>Acesso restrito</h1><p>Somente professores e administradores podem acessar este painel.</p><button onClick={()=>location.href='/'}>Voltar</button></main>
  return <main className="sf-shell"><header className="sf-hero"><button onClick={()=>location.href='/'}>← Portal</button><div><small>Checkpoint 14.6</small><h1>Moderação social</h1><p>Denúncias, decisões e histórico de segurança da comunidade.</p></div></header>{aviso&&<p className="sf-aviso">{aviso}</p>}<section className="sf-panel"><div className="sf-toolbar"><h2>Denúncias</h2><select value={filtro} onChange={e=>setFiltro(e.target.value)}><option value="aberta">Abertas</option><option value="em_analise">Em análise</option><option value="resolvida">Resolvidas</option><option value="arquivada">Arquivadas</option><option value="todas">Todas</option></select></div><div className="sf-reports">{lista.length===0?<p>Nenhuma denúncia nesta categoria.</p>:lista.map(d=><article key={d.id}><header><div><strong>{d.alvo_tipo}</strong><small>Enviado por {d.denunciante?.nome_personagem||d.denunciante?.usuario}</small></div><span>{d.status}</span></header><h3>{d.motivo}</h3><p>{d.detalhes||'Sem detalhes adicionais.'}</p><small>{new Date(d.criado_em).toLocaleString('pt-BR')}</small>{d.decisao&&<blockquote>{d.decisao}</blockquote>}<footer><button onClick={()=>resolver(d,'em_analise')}>Analisar</button><button onClick={()=>resolver(d,'resolvida')}>Resolver</button><button className="secondary" onClick={()=>resolver(d,'arquivada')}>Arquivar</button></footer></article>)}</div></section></main>
}