import { useEffect, useState } from 'react'
import { supabase } from '../services/supabase'
import '../styles/social-final.css'

export default function NotificacoesPresencaStandalone(){
  const [perfil,setPerfil]=useState(null),[notificacoes,setNotificacoes]=useState([]),[status,setStatus]=useState('online'),[aviso,setAviso]=useState('')
  useEffect(()=>{iniciar()},[])
  useEffect(()=>{if(!perfil?.id)return; const canal=supabase.channel(`notificacoes:${perfil.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'social_notificacoes',filter:`usuario_id=eq.${perfil.id}`},()=>carregar()).subscribe(); const timer=setInterval(()=>atualizarPresenca(status),60000); return()=>{supabase.removeChannel(canal);clearInterval(timer)}},[perfil?.id,status])
  async function iniciar(){const {data:{session}}=await supabase.auth.getSession(); if(!session)return; const {data:p}=await supabase.from('perfis').select('id,usuario,nome_personagem,avatar_url').eq('id',session.user.id).single(); setPerfil(p); const {data:pr}=await supabase.from('social_presenca').select('*').eq('usuario_id',session.user.id).maybeSingle(); if(pr?.status)setStatus(pr.status); await carregar(session.user.id); await atualizarPresenca(pr?.status||'online',session.user.id)}
  async function carregar(id=perfil?.id){if(!id)return; const {data,error}=await supabase.from('social_notificacoes').select('*').eq('usuario_id',id).order('criado_em',{ascending:false}).limit(100); if(error)return setAviso('Não foi possível carregar as notificações.'); setNotificacoes(data||[])}
  async function atualizarPresenca(novo,id=perfil?.id){if(!id)return; await supabase.from('social_presenca').upsert({usuario_id:id,status:novo,ultima_atividade:new Date().toISOString(),atualizado_em:new Date().toISOString()},{onConflict:'usuario_id'}); setStatus(novo)}
  async function marcar(id){await supabase.from('social_notificacoes').update({lida:true}).eq('id',id); setNotificacoes(n=>n.map(x=>x.id===id?{...x,lida:true}:x))}
  async function marcarTodas(){await supabase.from('social_notificacoes').update({lida:true}).eq('usuario_id',perfil.id).eq('lida',false); setNotificacoes(n=>n.map(x=>({...x,lida:true}))); setAviso('Notificações marcadas como lidas.')}
  if(!perfil)return <main className="sf-shell"><p>Carregando notificações...</p></main>
  const naoLidas=notificacoes.filter(n=>!n.lida).length
  return <main className="sf-shell"><header className="sf-hero"><button onClick={()=>location.href='/'}>← Portal</button><div><small>Checkpoint 14.5</small><h1>Notificações e presença</h1><p>Acompanhe convites, mensagens e interações sociais.</p></div><aside><strong>{naoLidas}</strong><span>não lidas</span></aside></header>{aviso&&<p className="sf-aviso">{aviso}</p>}<section className="sf-grid sf-notif-grid"><aside className="sf-panel"><h2>Minha presença</h2><select value={status} onChange={e=>atualizarPresenca(e.target.value)}><option value="online">Online</option><option value="ocupado">Ocupado</option><option value="ausente">Ausente</option><option value="invisivel">Invisível</option></select><p>O status é atualizado automaticamente enquanto você usa o site.</p><button onClick={marcarTodas}>Marcar todas como lidas</button></aside><section className="sf-panel sf-main"><h2>Central de notificações</h2><div className="sf-notifications">{notificacoes.length===0?<p>Nenhuma notificação ainda.</p>:notificacoes.map(n=><button key={n.id} className={n.lida?'':'nao-lida'} onClick={()=>{marcar(n.id);if(n.url)location.href=n.url}}><div><strong>{n.titulo}</strong><p>{n.corpo}</p><small>{new Date(n.criado_em).toLocaleString('pt-BR')}</small></div><span>{n.tipo}</span></button>)}</div></section></section></main>
}