import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../services/supabase'
import '../styles/social-final.css'

export default function ServidoresStandalone(){
  const [perfil,setPerfil]=useState(null),[servidores,setServidores]=useState([]),[membros,setMembros]=useState([]),[canais,setCanais]=useState([]),[mensagens,setMensagens]=useState([]),[servidor,setServidor]=useState(null),[canal,setCanal]=useState(null),[texto,setTexto]=useState(''),[novo,setNovo]=useState({nome:'',descricao:'',publico:true}),[codigo,setCodigo]=useState(''),[aviso,setAviso]=useState('')
  useEffect(()=>{iniciar()},[])
  useEffect(()=>{if(!canal?.id)return; carregarMensagens(canal.id); const ch=supabase.channel(`canal:${canal.id}`).on('postgres_changes',{event:'*',schema:'public',table:'social_canal_mensagens',filter:`canal_id=eq.${canal.id}`},()=>carregarMensagens(canal.id)).subscribe(); return()=>supabase.removeChannel(ch)},[canal?.id])
  async function iniciar(){const {data:{session}}=await supabase.auth.getSession(); if(!session)return; const [p,s,m,c]=await Promise.all([supabase.from('perfis').select('id,usuario,nome_personagem,avatar_url,cargo').eq('id',session.user.id).single(),supabase.from('social_servidores').select('*').order('criado_em',{ascending:false}),supabase.from('social_servidor_membros').select('*'),supabase.from('social_canais').select('*').order('ordem')]); setPerfil(p.data); setServidores(s.data||[]); setMembros(m.data||[]); setCanais(c.data||[])}
  const meus=useMemo(()=>servidores.filter(s=>membros.some(m=>m.servidor_id===s.id&&m.usuario_id===perfil?.id&&!m.banido)),[servidores,membros,perfil])
  const cargoAtual=membros.find(m=>m.servidor_id===servidor?.id&&m.usuario_id===perfil?.id)?.cargo
  const podeGerir=['dono','moderador'].includes(cargoAtual)
  async function criar(e){e.preventDefault(); const {error}=await supabase.rpc('social_criar_servidor',{p_nome:novo.nome,p_descricao:novo.descricao,p_publico:novo.publico,p_icone_url:null}); if(error)return setAviso(error.message); setNovo({nome:'',descricao:'',publico:true}); setAviso('Servidor criado.'); iniciar()}
  async function entrar(e){e.preventDefault(); const {error}=await supabase.rpc('social_entrar_servidor',{p_servidor:null,p_codigo:codigo}); if(error)return setAviso(error.message); setCodigo(''); setAviso('Você entrou no servidor.'); iniciar()}
  async function abrirServidor(s){setServidor(s); const cs=canais.filter(c=>c.servidor_id===s.id); setCanal(cs[0]||null)}
  async function carregarMensagens(id){const {data,error}=await supabase.from('social_canal_mensagens').select('*,autor:perfis!social_canal_mensagens_autor_id_fkey(id,usuario,nome_personagem,avatar_url)').eq('canal_id',id).order('criado_em'); if(error)return setAviso('Não foi possível carregar o canal.'); setMensagens(data||[])}
  async function enviar(e){e.preventDefault(); if(!texto.trim()||!canal)return; const {error}=await supabase.rpc('social_enviar_mensagem_canal',{p_canal:canal.id,p_conteudo:texto.trim(),p_resposta:null}); if(error)return setAviso(error.message); setTexto(''); carregarMensagens(canal.id)}
  async function criarCanal(){const nome=prompt('Nome do canal'); if(!nome)return; const {error}=await supabase.rpc('social_criar_canal',{p_servidor:servidor.id,p_nome:nome,p_descricao:'',p_somente_moderacao:false}); if(error)return setAviso(error.message); setAviso('Canal criado.'); iniciar()}
  if(!perfil)return <main className="sf-shell"><p>Carregando servidores...</p></main>
  return <main className="sf-shell"><header className="sf-hero"><button onClick={()=>location.href='/'}>← Portal</button><div><small>Checkpoint 14.4</small><h1>Servidores e canais</h1><p>Espaços sociais para estudo, RPG e convivência.</p></div></header>{aviso&&<p className="sf-aviso">{aviso}</p>}<section className="sf-grid"><aside className="sf-panel"><h2>Meus servidores</h2>{meus.map(s=><button className={servidor?.id===s.id?'ativo':''} key={s.id} onClick={()=>abrirServidor(s)}><strong>{s.nome}</strong><small>{s.publico?'Público':'Privado'}</small></button>)}<form onSubmit={entrar}><input value={codigo} onChange={e=>setCodigo(e.target.value)} placeholder="Código de convite"/><button>Entrar</button></form><form onSubmit={criar}><h3>Criar servidor</h3><input required minLength="3" value={novo.nome} onChange={e=>setNovo({...novo,nome:e.target.value})} placeholder="Nome"/><textarea value={novo.descricao} onChange={e=>setNovo({...novo,descricao:e.target.value})} placeholder="Descrição"/><label><input type="checkbox" checked={novo.publico} onChange={e=>setNovo({...novo,publico:e.target.checked})}/> Público</label><button>Criar</button></form></aside><section className="sf-panel sf-main">{!servidor?<div className="sf-empty"><h2>Escolha um servidor</h2></div>:<><header className="sf-server-head"><div><h2>{servidor.nome}</h2><p>{servidor.descricao}</p><small>Convite: {servidor.codigo_convite}</small></div>{podeGerir&&<button onClick={criarCanal}>+ Canal</button>}</header><nav className="sf-channels">{canais.filter(c=>c.servidor_id===servidor.id).map(c=><button className={canal?.id===c.id?'ativo':''} key={c.id} onClick={()=>setCanal(c)}># {c.nome}</button>)}</nav><div className="sf-messages">{mensagens.map(m=><article key={m.id}><strong>{m.autor?.nome_personagem||m.autor?.usuario}</strong><p>{m.apagada?'Mensagem apagada':m.conteudo}</p><small>{new Date(m.criado_em).toLocaleString('pt-BR')}</small></article>)}</div>{canal&&<form className="sf-chat-form" onSubmit={enviar}><textarea rows="2" value={texto} onChange={e=>setTexto(e.target.value)} placeholder={`Mensagem em #${canal.nome}`}/><button>Enviar</button></form>}</>}</section></section></main>
}