import { useEffect,useMemo,useState } from 'react'
import { supabase } from '../services/supabase'
import '../styles/temporadas.css'

const nomesTipo={aula:'Aulas',missao:'Missões',exploracao:'Exploração',evento:'Eventos',biblioteca:'Biblioteca',comercio:'Comércio',trabalho:'Profissões',jornal:'Jornal'}
const nomesRecompensa={ipes:'Ipês',xp:'XP de personagem',titulo:'Título de perfil',reputacao:'Reputação',item:'Item'}

export default function Temporadas({onVoltar}){
 const [dados,setDados]=useState(null),[desafios,setDesafios]=useState([]),[progresso,setProgresso]=useState([]),[recompensas,setRecompensas]=useState([]),[resgatadas,setResgatadas]=useState([]),[historico,setHistorico]=useState([]),[aba,setAba]=useState('temporada'),[mensagem,setMensagem]=useState(''),[acao,setAcao]=useState(false),[admin,setAdmin]=useState(false),[listaAdmin,setListaAdmin]=useState([]),[form,setForm]=useState({id:null,codigo:'',nome:'',tema:'',descricao:'',inicio_em:'',fim_em:'',status:'rascunho',niveis:20,xp_por_nivel:100,meta_global:5000})
 useEffect(()=>{carregar()},[])
 async function carregar(){setMensagem('');const{data:{user}}=await supabase.auth.getUser();if(!user){setMensagem('Entre na sua conta para acessar as temporadas.');return}const[{data:atual,error},{data:perfil}]=await Promise.all([supabase.rpc('obter_temporada_atual'),supabase.from('perfis').select('cargo').eq('id',user.id).maybeSingle()]);if(error){setMensagem(error.message);return}setAdmin(['administrador','admin'].includes(String(perfil?.cargo||'').toLowerCase()));setDados(atual);if(atual?.ativa){const tid=atual.temporada.id;const [{data:d},{data:p},{data:r},{data:rr}]=await Promise.all([supabase.from('temporada_desafios').select('*').eq('temporada_id',tid).eq('ativa',true).order('ordem'),supabase.from('temporada_desafios_usuarios').select('*').eq('usuario_id',user.id),supabase.from('temporada_recompensas').select('*').eq('temporada_id',tid).order('nivel'),supabase.from('temporada_recompensas_resgatadas').select('recompensa_id').eq('usuario_id',user.id)]);setDesafios(d||[]);setProgresso(p||[]);setRecompensas(r||[]);setResgatadas((rr||[]).map(x=>x.recompensa_id))}const{data:h}=await supabase.from('temporadas').select('id,nome,tema,inicio_em,fim_em,status').in('status',['encerrada','arquivada']).order('fim_em',{ascending:false});setHistorico(h||[]);if(['administrador','admin'].includes(String(perfil?.cargo||'').toLowerCase())){const{data:l}=await supabase.rpc('listar_temporadas_administracao');setListaAdmin(l||[])}}
 const t=dados?.temporada,u=dados?.progresso,xp=u?.xp||0,nivel=u?.nivel||1,metaNivel=t?.xp_por_nivel||100,progressoNivel=Math.min(100,Math.round(((xp%metaNivel)/metaNivel)*100)),progressoGlobal=t?Math.min(100,Math.round((t.progresso_global_atual/t.progresso_global_meta)*100)):0
 const progMap=useMemo(()=>Object.fromEntries(progresso.map(p=>[p.desafio_id,p])),[progresso])
 async function resgatarDesafio(p){setAcao(true);setMensagem('');const{data,error}=await supabase.rpc('resgatar_xp_desafio_sazonal',{p_desafio_usuario_id:p.id});setMensagem(error?error.message:`+${data.xp_ganho} XP sazonal recebido.`);await carregar();setAcao(false)}
 async function resgatarRecompensa(r){setAcao(true);setMensagem('');const{data,error}=await supabase.rpc('resgatar_recompensa_sazonal',{p_recompensa_id:r.id});if(error){setMensagem(error.message||'Não foi possível resgatar a recompensa.')}else{const detalhe=data?.tipo==='titulo'?data?.titulo:`${data?.quantidade??r.quantidade} ${nomesRecompensa[data?.tipo]||data?.tipo||''}`;setMensagem(`Recompensa resgatada: ${detalhe}.`)}await carregar();setAcao(false)}
 async function salvarTemporada(e){e.preventDefault();setAcao(true);const{error}=await supabase.rpc('salvar_temporada_administracao',{p_id:form.id,p_codigo:form.codigo,p_nome:form.nome,p_tema:form.tema,p_descricao:form.descricao,p_inicio_em:form.inicio_em,p_fim_em:form.fim_em,p_status:form.status,p_niveis:Number(form.niveis),p_xp_por_nivel:Number(form.xp_por_nivel),p_meta_global:Number(form.meta_global)});setMensagem(error?error.message:'Temporada salva.');await carregar();setAcao(false)}
 if(!dados)return <main className="temporadas-pagina"><button onClick={onVoltar||(()=>location.href='/')}>← Voltar</button><p>{mensagem||'Carregando temporada...'}</p></main>
 return <main className="temporadas-pagina"><button className="temporadas-voltar" onClick={onVoltar||(()=>location.href='/')}>← Voltar</button><header className="temporadas-hero"><p>Checkpoint 18</p><h1>{t?.nome||'Temporadas de Castelobruxo'}</h1><span>{t?.tema||'Nenhuma temporada ativa'}</span>{t&&<small>{new Date(t.inicio_em).toLocaleDateString('pt-BR')} — {new Date(t.fim_em).toLocaleDateString('pt-BR')}</small>}</header><nav className="temporadas-abas"><button className={aba==='temporada'?'ativo':''} onClick={()=>setAba('temporada')}>Temporada</button><button className={aba==='trilha'?'ativo':''} onClick={()=>setAba('trilha')}>Trilha de recompensas</button><button className={aba==='arquivo'?'ativo':''} onClick={()=>setAba('arquivo')}>Arquivo</button>{admin&&<button className={aba==='admin'?'ativo':''} onClick={()=>setAba('admin')}>Administração</button>}</nav>{mensagem&&<p className="temporadas-mensagem">{mensagem}</p>}
 {aba==='temporada'&&t&&<><section className="temporada-resumo"><div><small>Nível sazonal</small><strong>{nivel}</strong><span>{xp} XP</span><i><em style={{width:`${progressoNivel}%`}}/></i></div><div><small>Progresso global</small><strong>{t.progresso_global_atual}/{t.progresso_global_meta}</strong><i><em style={{width:`${progressoGlobal}%`}}/></i></div><div><small>Desafios concluídos</small><strong>{u?.desafios_concluidos||0}</strong></div></section><section className="desafios-area"><header><p>18.4 — Progressão sazonal</p><h2>Desafios</h2></header><div className="desafios-grade">{desafios.map(d=>{const p=progMap[d.id],feito=p?.concluido,recebido=p?.recompensa_recebida;return <article key={d.id}><small>{d.periodicidade} · {nomesTipo[d.objetivo_tipo]}</small><h3>{d.titulo}</h3><p>{d.descricao}</p><div className="desafio-progresso"><span>{p?.progresso||0}/{d.meta}</span><i><em style={{width:`${Math.min(100,((p?.progresso||0)/d.meta)*100)}%`}}/></i></div><button disabled={!feito||recebido||acao||!p} onClick={()=>resgatarDesafio(p)}>{recebido?'Recebido':feito?`Resgatar ${d.recompensa_xp_sazonal} XP`:'Em progresso'}</button></article>})}</div></section></>}
 {aba==='trilha'&&t&&<section className="trilha-area"><header><p>Trilha gratuita</p><h2>Recompensas da temporada</h2></header><div className="trilha-grade">{recompensas.map(r=>{const liberada=nivel>=r.nivel,resgatada=resgatadas.includes(r.id);return <article key={r.id} className={liberada?'liberada':'bloqueada'}><span>Nível {r.nivel}</span><strong>{r.descricao}</strong><small>{r.tipo==='ipes'?`${r.quantidade} Ipês`:r.tipo==='xp'?`${r.quantidade} XP`:r.tipo==='titulo'?r.titulo_perfil:r.tipo==='reputacao'?`${r.quantidade} reputação`:r.tipo}</small><button disabled={!liberada||resgatada||acao} onClick={()=>resgatarRecompensa(r)}>{resgatada?'Resgatada':liberada?(acao?'Resgatando...':'Resgatar'):`Exige nível ${r.nivel}`}</button></article>})}</div></section>}
 {aba==='arquivo'&&<section className="arquivo-temporadas"><header><p>Histórico</p><h2>Temporadas anteriores</h2></header>{historico.length===0?<p>Nenhuma temporada encerrada ainda.</p>:historico.map(h=><article key={h.id}><strong>{h.nome}</strong><span>{h.tema}</span><small>{new Date(h.inicio_em).toLocaleDateString('pt-BR')} — {new Date(h.fim_em).toLocaleDateString('pt-BR')}</small></article>)}</section>}
 {aba==='admin'&&admin&&<section className="temporadas-admin"><header><p>18.3 — Gestão sazonal</p><h2>Painel de temporadas</h2></header><form onSubmit={salvarTemporada}><input placeholder="Código" value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})} required/><input placeholder="Nome" value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})} required/><input placeholder="Tema" value={form.tema} onChange={e=>setForm({...form,tema:e.target.value})} required/><textarea placeholder="Descrição" value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/><label>Início<input type="datetime-local" value={form.inicio_em} onChange={e=>setForm({...form,inicio_em:e.target.value})} required/></label><label>Fim<input type="datetime-local" value={form.fim_em} onChange={e=>setForm({...form,fim_em:e.target.value})} required/></label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="rascunho">Rascunho</option><option value="ativa">Ativa</option><option value="encerrada">Encerrada</option><option value="arquivada">Arquivada</option></select><input type="number" min="1" max="100" value={form.niveis} onChange={e=>setForm({...form,niveis:e.target.value})}/><input type="number" min="1" value={form.xp_por_nivel} onChange={e=>setForm({...form,xp_por_nivel:e.target.value})}/><input type="number" min="1" value={form.meta_global} onChange={e=>setForm({...form,meta_global:e.target.value})}/><button disabled={acao}>{acao?'Salvando...':'Salvar temporada'}</button></form><div className="temporadas-admin-lista">{listaAdmin.map(x=><article key={x.id} onClick={()=>setForm({id:x.id,codigo:x.codigo,nome:x.nome,tema:x.tema,descricao:'',inicio_em:x.inicio_em?.slice(0,16),fim_em:x.fim_em?.slice(0,16),status:x.status,niveis:x.niveis_totais,xp_por_nivel:x.xp_por_nivel,meta_global:x.progresso_global_meta})}><strong>{x.nome}</strong><span>{x.status} · {x.participantes} participantes</span><small>{x.progresso_global_atual}/{x.progresso_global_meta} XP global</small></article>)}</div></section>}
 </main>
}