import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import './styles/mobile-final.css'
import { iniciarPontePerfilSocial } from './socialProfileBridge.jsx'

const root = createRoot(document.getElementById('root'))
function mostrarErro(error){console.error('Falha ao iniciar Castelobruxo:',error);root.render(<main style={{maxWidth:'760px',margin:'60px auto',padding:'28px',color:'#eee7d7',background:'rgba(17,25,20,.96)',border:'1px solid rgba(201,164,92,.45)',borderRadius:'18px',fontFamily:'system-ui,sans-serif'}}><h1 style={{color:'#e5c16b'}}>Castelobruxo não conseguiu iniciar</h1><p>A publicação foi concluída, mas ocorreu um erro ao carregar o aplicativo.</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',padding:'16px',background:'#090e0b',borderRadius:'10px'}}>{error?.message||String(error)}</pre><button type="button" onClick={()=>window.location.reload()}>Tentar novamente</button></main>)}
function acompanharCarregamentoDoPerfil(){let segundos=0;const timer=window.setInterval(()=>{segundos+=1;const texto=(document.body?.innerText||'').toLowerCase();const travado=texto.includes('carregando perfil')||texto.includes('carregando seu perfil');if(!travado){window.clearInterval(timer);sessionStorage.removeItem('castelobruxo:perfil-retry');return}if(segundos===10&&!document.getElementById('aviso-perfil-mobile')){const aviso=document.createElement('div');aviso.id='aviso-perfil-mobile';aviso.style.cssText='position:fixed;inset:auto 12px 18px;z-index:999999;padding:16px;background:#172019;color:#f3ead2;border:1px solid #c9a45c;border-radius:14px;box-shadow:0 12px 30px rgba(0,0,0,.45);font-family:system-ui,sans-serif;text-align:center';aviso.innerHTML='<strong style="display:block;color:#efd078;margin-bottom:8px">O perfil está demorando</strong><span style="display:block;margin-bottom:12px">Sua sessão será mantida. Tente carregar novamente.</span><button id="recarregar-perfil-castelobruxo" style="padding:11px 16px;border-radius:9px">Tentar novamente</button>';document.body.appendChild(aviso);document.getElementById('recarregar-perfil-castelobruxo')?.addEventListener('click',()=>window.location.reload())}if(segundos>=20&&sessionStorage.getItem('castelobruxo:perfil-retry')!=='1'){sessionStorage.setItem('castelobruxo:perfil-retry','1');window.clearInterval(timer);window.location.reload()}},1000)}
async function renderizarPagina(Pagina,SidebarGlobal){root.render(<StrictMode><SidebarGlobal/><Pagina/></StrictMode>)}
async function iniciar(){try{acompanharCarregamentoDoPerfil();const path=window.location.pathname;const{default:SidebarGlobal}=await import('./components/layout/SidebarGlobal.jsx')
if(path.startsWith('/rpg')){const[{default:RpgCenas},{default:PainelTestesGlobal},{default:PainelItensGlobal},{default:PainelRecompensasGlobal},{default:PainelNpcsGlobal},{default:PainelCampanhasGlobal},{default:CentralNarradorGlobal}]=await Promise.all([import('./pages/RpgCenas.jsx'),import('./components/rpg/PainelTestesGlobal.jsx'),import('./components/rpg/PainelItensGlobal.jsx'),import('./components/rpg/PainelRecompensasGlobal.jsx'),import('./components/rpg/PainelNpcsGlobal.jsx'),import('./components/rpg/PainelCampanhasGlobal.jsx'),import('./components/rpg/CentralNarradorGlobal.jsx')]);root.render(<StrictMode><SidebarGlobal/><RpgCenas/><PainelTestesGlobal/><PainelItensGlobal/><PainelRecompensasGlobal/><PainelNpcsGlobal/><PainelCampanhasGlobal/><CentralNarradorGlobal/></StrictMode>);return}
if(path.startsWith('/guia')){const{default:Pagina}=await import('./pages/GuiaInicio.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/rotina')){const{default:Pagina}=await import('./pages/RotinaEscolarStandalone.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/tribos')){const{default:Pagina}=await import('./pages/TribosCompletasStandalone.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/chat')){const{default:Pagina}=await import('./pages/ChatPrivadoStandalone.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/mural')){const{default:Pagina}=await import('./pages/MuralComunidadeStandalone.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/servidores')){const{default:Pagina}=await import('./pages/ServidoresStandalone.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/notificacoes')){const{default:Pagina}=await import('./pages/NotificacoesPresencaStandalone.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/moderacao-social')){const{default:Pagina}=await import('./pages/ModeracaoSocialStandalone.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/comunidade')){const{default:Pagina}=await import('./pages/ComunidadeSocialStandalone.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/exploracao')||path.startsWith('/colecoes')){const{default:Pagina}=await import('./pages/ExploracaoColecoesStandalone.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/temporadas')){const{default:Pagina}=await import('./pages/Temporadas.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/jornal')){const{default:Pagina}=await import('./pages/JornalCastelobruxo.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/admin-profissoes')){const{default:Pagina}=await import('./pages/PainelProfissoesAdmin.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/profissoes')){const{default:Pagina}=await import('./pages/Profissoes.jsx');await renderizarPagina(Pagina,SidebarGlobal);return}
if(path.startsWith('/dormitorio')){window.location.replace('/');return}
const{default:App}=await import('./App.jsx');root.render(<StrictMode><SidebarGlobal/><App/></StrictMode>);iniciarPontePerfilSocial();const destino=new URLSearchParams(window.location.search).get('pagina');if(destino){window.setTimeout(()=>{window.dispatchEvent(new CustomEvent('castelobruxo:navegar',{detail:{pagina:destino}}));window.history.replaceState({},'','/')},250)}}catch(error){mostrarErro(error)}}
iniciar()
// publicação pública: não usar URLs técnicas de deployment
